### ISSUE TITLE
ROC-SCORE

### ISSUE THREAD

**Issue by stanveer-97** [mmayers12/hetnet-ml#1]
I was wondering about computation of ROC/AUROC score using the calculated DWPC scores.

**Comment by mmayers12** [comment]
So DWPC is just a numerical feature between two entities in a graph. You have to train a model using these values as features on a known set of relations to get to ROC/AUROC calculations.

So for example in Drug Repositioning, you have a set of Compound Disease pairs some with a known Compound-Treats-Disease relationship, others with a Compound-Does_not_treat-Disease relationship. For these pairs you would extract DWPC values for the various path-types that connect them. Then you would use these DWPC values and a subset of say 80% your known Compound Disease pairs to train a model, like a Logistic Regression, to learn this Treats vs Does_not_treat relationship. You then see how well your model is able to identify the Treats vs Does_not_treat relationships in your remaining 20% of known pairs, and can compute the ROC/AUROC scores from this result.
